let components : Array<any> = [];


export { BaseComponent } from './base.component';
export { InputComponent } from './input.component';
export { JqueryComponent } from './jquery.component';
export { InputJqueryComponent } from './input.jquery.component';
export { DefaultJqueryComponent } from './default.jquery.component';

import { InputTextComponent } from './input.text.component';
export { InputTextComponent } from './input.text.component';
components.push(InputTextComponent);
import { InputRichtextComponent } from './input.richtext.component';
export { InputRichtextComponent } from './input.richtext.component';
components.push(InputRichtextComponent);
import { InputCheckboxComponent } from './input.checkbox.component';
export { InputCheckboxComponent } from './input.checkbox.component';
components.push(InputCheckboxComponent);
import { LookupGridComponent } from './lookup.grid.component';
export { LookupGridComponent } from './lookup.grid.component';
components.push(LookupGridComponent);
import { PanelComponent } from './panel.component';
export { PanelComponent } from './panel.component';
components.push(PanelComponent);
import { InputRadiogroupComponent } from './input.radiogroup.component';
export { InputRadiogroupComponent } from './input.radiogroup.component';
components.push(InputRadiogroupComponent);
import { SubmitButtonComponent } from './submit.button.component';
export { SubmitButtonComponent } from './submit.button.component';
components.push(SubmitButtonComponent);
import { DivRowComponent } from './div.row.component';
export { DivRowComponent } from './div.row.component';
components.push(DivRowComponent);
import { ModalComponent } from './modal.component';
export { ModalComponent } from './modal.component';
components.push(ModalComponent);
import { AsyncOutputComponent } from './async.output.component';
export { AsyncOutputComponent } from './async.output.component';
components.push(AsyncOutputComponent);
import { InputTimeComponent } from './input.time.component';
export { InputTimeComponent } from './input.time.component';
components.push(InputTimeComponent);
import { InputNumberComponent } from './input.number.component';
export { InputNumberComponent } from './input.number.component';
components.push(InputNumberComponent);
import { FormElementComponent } from './form.element.component';
export { FormElementComponent } from './form.element.component';
components.push(FormElementComponent);
import { InputDatetimeComponent } from './input.datetime.component';
export { InputDatetimeComponent } from './input.datetime.component';
components.push(InputDatetimeComponent);
import { DdMenuComponent } from './dd.menu.component';
export { DdMenuComponent } from './dd.menu.component';
components.push(DdMenuComponent);
import { MenuItemComponent } from './menu.item.component';
export { MenuItemComponent } from './menu.item.component';
components.push(MenuItemComponent);
import { InputLookupComponent } from './input.lookup.component';
export { InputLookupComponent } from './input.lookup.component';
components.push(InputLookupComponent);
import { InputDateComponent } from './input.date.component';
export { InputDateComponent } from './input.date.component';
components.push(InputDateComponent);
import { InputCurrencyComponent } from './input.currency.component';
export { InputCurrencyComponent } from './input.currency.component';
components.push(InputCurrencyComponent);
import { DivColComponent } from './div.col.component';
export { DivColComponent } from './div.col.component';
components.push(DivColComponent);
import { InputSelectComponent } from './input.select.component';
export { InputSelectComponent } from './input.select.component';
components.push(InputSelectComponent);
import { InputTextareaComponent } from './input.textarea.component';
export { InputTextareaComponent } from './input.textarea.component';
components.push(InputTextareaComponent);
import { CommandButtonComponent } from './command.button.component';
export { CommandButtonComponent } from './command.button.component';
components.push(CommandButtonComponent);
import { LinkButtonComponent } from './link.button.component';
export { LinkButtonComponent } from './link.button.component';
components.push(LinkButtonComponent);
import { InlineLoaderComponent } from './inline.loader.component';
export { InlineLoaderComponent } from './inline.loader.component';
components.push(InlineLoaderComponent);

export const BONG_COMPONENTS = components;